QuizApp/QuizApp/urls.py
from django.contrib import admin
from django.urls import path
from quiz import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/",views.RegistrationView.as_view(),name="register"),
    path("",views.SignInView.as_view(),name="signin"),



    path("signout",views.signout,name="logout"),
    path("quiz/home",views.QuizHomeView.as_view(),name="home"),

    path("questions/all/<str:cat>/<str:mode>/",views.QuestionListView.as_view(),name="question-list"),
    
]

QuizApp/quiz/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Category(models.Model):
    opt=(
        ("python" ,"python"),
        ("html","html"),
        ("css","css"),
        ("bootstrap","bootstrap"),
        ("django","django"),
        ("mysql","mysql")
    )
    topic=models.CharField(max_length=100,choices=opt)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.topic





    
class Questions(models.Model):
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)
    options=(
        ("easy","easy"),
        ("medium","medium"),
        ("hard","hard")
    )
    mode=models.CharField(max_length=200,choices=options,default="easy")
    mark=models.PositiveIntegerField(default=2)
    question=models.CharField(max_length=200)

    @property
    def choices(self):
        return Answers.objects.filter(question=self)
    
    @property
    def answer(self):
        return Answers.objects.get(question=self,is_correct=True)
    
    
    
    def __str__(self) -> str:
        return self.question

class Answers(models.Model):
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)
    options=models.CharField(max_length=200)
    is_correct=models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.options
	
class QuizRecord(models.Model):
    mark_obtained=models.PositiveIntegerField()
    right_answer_count=models.PositiveIntegerField()
    wrong_answer_count=models.PositiveIntegerField()
    user=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    date=models.DateField(auto_now_add=True)
 

    

QuizApp/quiz/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["username","password1","password2","email"]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput())

QuizApp/quiz/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.models import User

from quiz.models import Category,Questions,Answers,QuizRecord
from quiz.forms import RegistrationForm,LoginForm

from django.contrib.auth import login,logout,authenticate

from django.urls import reverse_lazy

from django.views.generic import CreateView,ListView,UpdateView,DetailView,TemplateView,View,FormView

# Create your views here.


class RegistrationView(CreateView):
    
    model=User
    form_class=RegistrationForm
    template_name="register.html"
    success_url=reverse_lazy("signin")
    

class SignInView(FormView):
    form_class=LoginForm
    template_name="login.html"
    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("home")
        return render(request,self.template_name,{"form":form})
        
            

class HomeView(TemplateView):
    template_name="home.html"



def signout(request,*args,**kwargs):
    logout(request)
    return redirect("signin")


class QuizHomeView(View):
    def get(self,request,*args,**kwargs):
        qs=Category.objects.all()
        return render(request,"quiz-home.html",{"cats":qs})
    
    def post(self,request,*args,**kwargs):
        
        cat=request.POST.get("category")
        mode=request.POST.get("mode")
        return redirect("question-list",cat=cat,mode=mode)
    



from django.db.models import Sum
    

class QuestionListView(View):

    def get(self,request,*args,**kwargs):
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        qs=list(Questions.objects.filter(category__topic=category,mode=mode))
        return render(request,"question-list.html",{"questions":qs})
    
    def post(self,request,*args,**kwargs):
        data=request.POST.dict()
        print(data)
        data.pop('csrfmiddlewaretoken')
        questions_attended=len(data)
       
        mark_obtained=0
        wrong_answer=0
        for q,ans in data.items():
            question=Questions.objects.get(question=q)
            right_answer=question.answer
            if(right_answer.options==ans):
                mark_obtained=mark_obtained+question.mark
            else:
                wrong_answer+=1

            right_answer_count=questions_attended-wrong_answer
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        result=''
        total=Questions.objects.filter(category__topic=category,mode=mode).aggregate(Sum('mark')).get('mark__sum')
        if total/2 <=mark_obtained:
            result="pass"
        else:
            result="failed"
        data=QuizRecord.objects.create(mark_obtained=mark_obtained,right_answer_count=right_answer_count,wrong_answer_count=wrong_answer,user=request.user)
        return render(request,"quiz-mark.html",{'mark_obtained':mark_obtained,'question_attended':questions_attended,"result":result})
    

QuizApp/quiz/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
 
    <style>
    body{
            background-color: #7c1e97;

        }
    </style>
</head>
<body>


    


    <div class="container mt-5"  >
        <div class="row" >
            <div class="col-4" ></div>
            <div class="col-4" id="id_b">
                <strong class="text-center"><center><h3>Login Form</h3></center></strong>
                <form action="" method="post" class="mt-5">
                    {%csrf_token%}
                    {{form.as_p}}
                    <!-- <button type="submit">login</button> -->
                    <center>
                        <button type="submit" value="login" class="btn btn-primary rounded-pill">
                            Login

                        </button>

                    </center>
                </form>
                <div class="text-center mt-5">
                    <h6>not registered  <a href="{%url 'register'%}">register here</a></h6>

                </div>

            </div>
            
            <div class="col-4"></div>
        </div>
    </div>
    
</body>
</html>

QuizApp/quiz/templates/question-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    
</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="#">
            <img src="" alt="quiz hub" width="30" height="24">
          </a>

          <a href="{%url 'logout'%}">Logout</a>
        </div>
      </nav>


      
    <h1 class="text-center mt-5 " ><strong>Quiz Hub</strong></h1>


    <div class="container border rounded p-2 mt-4">
        <form action="" method="post">
            {%csrf_token%}
            {%for q in questions%}
           <div class="border border-bottom mb-3">
              <h4>{{forloop.counter}}   ] {{q.question}} marks ({{q.mark}})</h4>

            <div style="height: 80px;">

              {%for ch in q.choices%}
              <span class="p-2"><input type="radio" name="{{q}}" value="{{ch}}">{{ch}}</span>


              {%endfor%}
            
            </div>


           </div>
        {%endfor%}
        <button type="submit" class="btn btn-outline-dark rounded">submit</button>
        </form>



    </div>
    
</body>
</html>

QuizApp/quiz/templates/quiz-home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    
    <style>
        #id_d{
            background-color: rgb(7, 92, 64);
        }
    </style>


</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="#">
            <img src="" alt="quiz hub" width="30" height="24">
          </a>

          <a href="{%url 'logout'%}">Logout</a>
        </div>
      </nav>


      
    <h1 class="text-center mt-5 " ><strong>Quiz Hub</strong></h1>
    <h4 class="text-center mt-5 " >Choose your Category</h4>

    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 shadow p-3" id="id_d">
                <form action="" method="post">
                    {%csrf_token%}
                    

                    <label for="id_cat">select a category</label>
                    <select name="category" id="id_cat" class="form-select mt-2 mb-2">
                        {%for cat in cats%}
                           <option value="{{cat.topic}}">{{cat.topic}}</option>    
                        {%endfor%}
                    </select>
                    <label for="id_mode">select a mode</label>

                    <select name="mode" id="id_mode" class="form-select">
                        <option value="easy">easy</option>
                        <option value="medium">medium</option>
                        <option value="hard">hard</option>
                    </select>
                    <input type="submit" value="lets start" class="btn btn-dark mt-5 rounded-pill">
                </form>


            </div>
            <div class="col-3"></div>
        </div>
    </div>
</body>
</html>

QuizApp/quiz/templates/quiz-mark.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marks</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
    <style>
        h4{
            color: #107917;
        }
    </style>
</head>
<body>

    <nav class="navbar bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="#">
            <img src="" alt="quiz hub" width="30" height="24">
          </a>

          <a href="{%url 'logout'%}">Logout</a>
        </div>
      </nav>


      
    <h1 class="text-center mt-5 " ><strong>Quiz Hub</strong></h1>

    <h4><strong class="text-center mt-5"><center>Score Card</center> </strong></h4>

    <div class="container">
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
          
                    <div class="card-body">
                      <h5 class="card-title">Score</h5>
                      <p class="card-text">Total marks : {{mark_obtained}}</p>
                      <p class="card-text">Question Attended : {{question_attended}}</p>
                      <p class="card-text">Result :{{result}}</p>
                      
                
                    </div>
                 
                  </div>
                
                        </div>

            </div>
            <div class="col-4"></div>
        </div>
    </div>

        
        
              

</body>
</html>

QuizApp/quiz/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <style>
        #id_div{
            
            background-color: #202b61;
            background-image: linear-gradient(43deg, #565d83 0%, #87e0da 46%, #2d271a 100%);

        }
        body{
            background-color: #75baec34;
            /* background-image: linear-gradient(190deg, #516b7a 0%, #80D0C7 50%, #eb7c7c 150%) ; */
            

        }
        h6{
            color:rgb(239, 247, 247)
        }

        


    </style>
   
</head>
<body>
    <div class="container mt-5"  >
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6" id="id_div" >

                <h3><center><strong>Registration Form</strong></center></h3>

                
                    <form action="" method="post">
                        {%csrf_token%}
                        {{form.as_p}}
                        <center>
                            <button type="submit" value="register" class="btn btn-primary rounded-pill">
                                Register Now

                            </button>
                        </center>
                    </form>
                    <div class="text-center mt-5">
                        <h6>already a user  <a href="{%url 'signin'%}">signin</a></h6>

                    </div>

                    
                  
                
            </div>
            <div class="col-3"></div>
        </div>
    </div>
    
</body>
</html>